INSERT INTO `container_cost` (`id`, `name`, `is_active`, `description`) VALUES
(1, 'DOC+BSC', 1, ''),
(2, 'FRET', 1, ''),
(3, 'transit', 1, ''),
(4, 'sydam', 1, ''),
(5, 'acconage', 1, ''),
(6, 'echange BL', 1, ''),
(7, 'Sursalaire', 1, ''),
(8, 'livraison', 1, ''),
(9, 'mise a terre', 1, ''),
(10, 'phyto', 1, ''),
(11, 'caution', 1, ''),
(12, 'Assurance', 1, ''),
(13, 'ts douane', 1, ''),
(14, 'ts darriv', 1, ''),
(15, 'frais divers', 1, ''),
(16, 'ts medlog', 1, ''),
(17, 'COC', 1, ''),
(18, 'TVA', 1, ''),
(19, 'DDE', 1, ''),
(20, 'Douane', 1, '');