INSERT INTO `currency`(`id`, `name`, `symbol`) VALUES ('1','FRANC CFA','F CFA'),
('2','EURO','€'),
('3','DOLLAR','$'),
('4','YEN','¥'),
('5','YUAN','¥'),
('6','DINAR TUNISIEN','DT'),
('7','OUGUIYA','أوقية'),
('8','HRYVNIA','₴'),
('9','CEDI','₵'),
('10','NAIRA','N'),
('11','RAND','R'),
('12','ROUBLE RUSSE','₽'),
('13','LARI','₾'),
('14','WON','￦'),
('15','TUGRIK','₮'),
('16','RIYAL','riyal'),
('17','DIRHAM','DH'),
('18','LIVRE STERLING','£'),
('19','RUPIAH','ROUPIE'),
('20','KIP','₭'),
('21','RINGGIT','RM'),
('22','ROUPIE','Rs'),
('23','BAHT','฿'),
('24','DONG','đồng'),
('25','REAL BRESILIEN','R$')
