    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (1,"BICICI",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (2,"NSIA BANQUE",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (3,"SIB",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (4,"SGBCI3",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (5,"CITIBANK CI",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (6,"BOA",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (7,"BANQUE ATLANTIQUE (BACI)",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (8,"ECOBANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (9,"BHCI",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (10,"BNI",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (11,"STANDARD CHARTERED BANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (12,"AFRILAND FIRST BANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (13,"VERSUS BANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (14,"ORABANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (15,"BRIDGE BANK GROUP (BBG - CI)",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (16,"UNITED BANK FOR AFRICA (UBA)",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (17,"BSIC - COTE D’IVOIRE",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (18,"BGFIBANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (19,"BANQUE POPULAIRE",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (20,"GTBANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (21,"CORIS BANK INTERNATIONAL",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (22,"BANQUE DE L’UNION (BDU-CI)",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (23,"STANBIC BANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (24,"BANQUE D'ABIDJAN",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (25,"MANSA BANK",NULL,NULL,NULL,1);
    INSERT INTO `bank`(`id`, `name`, `email`, `postal_box`, `phone`, `is_active`) VALUES (26,"ORANGE BANK",NULL,NULL,NULL,1);